#!/usr/bin/python
'''Simulates minions via a dump file'''

import argparse
from functools import partial
import logging
from multiprocessing import Process, cpu_count
import sys

import zmq
import zmq.eventloop.ioloop
import salt.log

from evil_minion import EvilMinion

def main():
    # parse commandline switches
    parser = argparse.ArgumentParser(description='Simulates a minion given a dump file.')
    parser.add_argument('master', help='the master to connect to')
    parser.add_argument('--count', dest='count', type=int, default=10,
                       help='number of evil minions (default: 10)')
    parser.add_argument('--processes', dest='processes', type=int, default=cpu_count(),
                       help='number of concurrent processes (default is the CPU count: %d)' % cpu_count())
    parser.add_argument('--dump-path', dest='dump_path', default='/tmp/minion-dump.yml',
                       help='path for the dump file (default: /tmp/minion-dump.yml)')
    args = parser.parse_args()

    # set up logging
    salt.log.setup_console_logger(log_level='debug')

    # set up processes
    chunks = minion_chunks(args.count, args.processes)
    for chunk in chunks:
        p = Process(target=process_main, args=(args, chunk))
        p.start()

def process_main(args, indexes):
    '''Per-process entry point'''
    # set up logging
    log = logging.getLogger(__name__)
    log.debug("Starting pool: %s" % indexes)

    # set up the IO loop
    zmq.eventloop.ioloop.install()
    io_loop = zmq.eventloop.ioloop.ZMQIOLoop.current()

    # start the evil!
    for i in indexes:
        evil_minion = EvilMinion(args.master, 'evil-%d' % i, args.dump_path, io_loop)
        io_loop.spawn_callback(evil_minion.start)
    io_loop.start()

def minion_chunks(count, processes):
    '''Returns chunks of minion indexes, per process (eg. 3 CPUs and 4 processes: [[0, 1], [2], [3]])'''
    minions_per_process = count / processes
    rest = count % processes
    lengths = [minions_per_process + 1] * rest + [minions_per_process] * (processes - rest)
    starts = [sum(lengths[:i]) for i in range(processes)]

    indexes = list(range(count))

    return [indexes[starts[i]:starts[i] + lengths[i]] for i in range(processes)]

if __name__ == "__main__":
    main()
