#!/usr/bin/python
'''Simulates minions via a dump file'''

import argparse

import zmq
import zmq.eventloop.ioloop
import salt.log

from evil_minion import EvilMinion

def main():
    # parse commandline switches
    parser = argparse.ArgumentParser(description='Simulates a minion given a dump file.')
    parser.add_argument('master', help='the master to connect to')
    parser.add_argument('--count', dest='count', type=int, default=10,
                       help='number of evil minions (default: 10)')
    parser.add_argument('--dump-path', dest='dump_path', default='/tmp/minion-dump.yml',
                       help='path for the dump file (default: /tmp/minion-dump.yml)')
    args = parser.parse_args()

    # set up logging
    salt.log.setup_console_logger(log_level='debug')

    # set up the IO loop
    zmq.eventloop.ioloop.install()
    io_loop = zmq.eventloop.ioloop.ZMQIOLoop.current()

    # start the evil!
    for i in range(args.count):
        evil_minion = EvilMinion(args.master, 'evil-%d' % i, args.dump_path, io_loop)
        io_loop.spawn_callback(evil_minion.start)
    io_loop.start()

if __name__ == "__main__":
    main()
