#!/usr/bin/env python
'''
Script to kick off salt-minion with a ZeroMQ Dumper attached.
The Dumper monkey-patches Salt core I/O classes to dump exchanged messages to a Yaml file.
'''

import distutils.spawn

import dumper

d = dumper.Dumper('/tmp/minion-trace.yml')
d.install()

execfile(distutils.spawn.find_executable('salt-minion'))
